OxxoWeb/Pages/Dashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OxxoWeb.Models;

namespace OxxoWeb.Pages;

public class DashboardModel : PageModel
{
    private readonly DataBaseContextPerfil _context; // Para poder usar ese database context para el tipo de usuario
    public Perfiles UsuarioPerfil { get; set; } // Obtener el tipo de sesión del usuario

    // Incluir el model en el servicio 
    public DashboardModel(DataBaseContextPerfil context)
    {
        _context = context;
    }
    public void OnGet()
    {
        
        // Checks if it has a user ID stored as int
        int? userId = HttpContext.Session.GetInt32("Id");
        if (userId == null)
        {
            // Takes user to login page
            Response.Redirect("/Index");
        }
        else 
        {
            // Cargar el perfil del usuario especificado
            UsuarioPerfil = _context.GetPerfil(userId.Value);

            

        }
    }
}

OxxoWeb/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OxxoWeb.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

OxxoWeb/Pages/Gerente.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OxxoWeb.Models;
using System.Collections.Generic;

namespace OxxoWeb.Pages
{
    public class GerenteModel : PageModel
    {
    
        public List<AsesorInfo> ListaAsesores { get; set; } = new();
        public Dictionary<int, int> tiendasPorAsesor { get; set; } = new();



        public void OnGet(){
            ReginaDataBaseContext db = new ReginaDataBaseContext();
            ListaAsesores = db.GetAsesoresInfo();
            tiendasPorAsesor = db.GetTiendasNum();

            // Asignar el count a cada asesor
            foreach (var asesor in ListaAsesores)
            {
                if (tiendasPorAsesor.TryGetValue(asesor.IdUsuario, out int count))
                {
                    asesor.TiendasCount = count;
                }
                else
                {
                    asesor.TiendasCount = 0;
                }
            }

            
        }


    }
}

OxxoWeb/Pages/GerentePanel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OxxoWeb.Models;
using System.Collections.Generic;

namespace GerenteTareas.Pages
{
    public class GerentePanelModel : PageModel
    {
        // ==========================================
        // Instancia a mi database context para acceder a la base de datos
        // ===========================================
        private readonly GaliDatabaseContext _db;

        // ==========================================
        // Constructor que inicializa el contexto de base de datos
        // ==========================================
        public GerentePanelModel()
        {
            _db = new GaliDatabaseContext();
        }

        // ==========================================
        // Propiedades para las KPIs 
        // ==========================================
        public int TotalAsesores { get; set; }
        public int MetasActivas { get; set; }
        public int PlazasRegistradas { get; set; }
        public int TiendasRegistradas { get; set; }
        public int TareasAsignadas { get; set; }
        public int TareasProximas { get; set; }

        // ==========================================
        // Propiedades para las progress bars
        // ==========================================
        public int CapacitacionesFinalizadas { get; set; }
        public int TotalEXP { get; set; }
        public int TotalCertificados { get; set; }
        public int PublicacionesRecientes { get; set; }

        // ==========================================
        // Propiedades para logros en equipo
        // ==========================================
        public bool LogroCapacitacionPorTodos { get; set; }
        public bool LogroEXP5000 { get; set; }
        public bool LogroCincoCertificados { get; set; }
        public bool LogroCincoPublicaciones { get; set; }
        public bool LogroAsesorCincoMetas { get; set; }
        public bool LogroTodosTiposCompletados { get; set; }

        // ==========================================
        // Propiedad para logros individuales - Ranking
        // ==========================================
        public List<(string NombreCompleto, int Total)> RankingAsesores { get; set; } = new();

        // ==========================================
        // Propiedad para la tabla de progreso
        // ==========================================
        public List<ProgresoAsesor> ProgresoAsesores { get; set; } = new();

        // ==========================================
        // Propiedad para capturar una nueva tarea para el formulario
        // ==========================================
        [BindProperty]
        public Tarea NuevaTarea { get; set; } = new Tarea(); // trae DateTime.Today por defecto

        public List<Usuario> Asesores { get; set; } = new List<Usuario>();

        // ==========================================
        // Método que se ejecuta al cargar la página
        // ==========================================
         public void OnGet()
        {
            // Mensaje en la terminal 
            bool conectado = _db.ProbarConexion();
            Console.WriteLine("¿Conexión exitosa? " + conectado);

            // Obtiene los valores para los KPIs
            TotalAsesores = _db.GetTotalAsesores();
            MetasActivas = _db.GetMetasActivas();
            PlazasRegistradas = _db.GetPlazasRegistradas();
            TiendasRegistradas = _db.GetTiendasRegistradas();
            TareasAsignadas = _db.GetTareasTotales();
            TareasProximas = _db.GetTareasProximasAVencer();

            // Obtener datos para la tabla "Progreso de Asesores"
            ProgresoAsesores = _db.GetProgresoAsesores();
            
            // Obtener asesores para el select del formulario
            Asesores = _db.GetAsesores();

            // Obtener métricas para las barras de progreso
            CapacitacionesFinalizadas = _db.GetCapacitacionesFinalizadas();
            TotalEXP = _db.GetTotalEXP();
            TotalCertificados = _db.GetTotalCertificados();
            PublicacionesRecientes = _db.GetPublicacionesRecientes();

            // Obtener logros del equipo
            LogroCapacitacionPorTodos = _db.Logro_CapacitacionPorTodos();
            LogroEXP5000 = _db.Logro_EXP5000();
            LogroCincoCertificados = _db.Logro_CincoCertificados();
            LogroCincoPublicaciones = _db.Logro_CincoPublicacionesRecientes();
            LogroAsesorCincoMetas = _db.Logro_AsesorCincoMetas();
            LogroTodosTiposCompletados = _db.Logro_TodosTiposCompletados();

           // Obtener ranking de asesores destacados
           RankingAsesores = _db.ObtenerTopAsesoresPorMetas();
        }
       
        // ==========================================
        // Método para insertar una nueva tarea
        // ==========================================
        public IActionResult OnPost()
         {
             if (!ModelState.IsValid || NuevaTarea.FechaLimite == DateTime.MinValue || NuevaTarea.IdUsuario == 0)
             {
                 TempData["Mensaje"] = "Por favor completa todos los campos correctamente.";
               
                TotalAsesores      = _db.GetTotalAsesores();
                MetasActivas       = _db.GetMetasActivas();
                PlazasRegistradas  = _db.GetPlazasRegistradas();
                TiendasRegistradas = _db.GetTiendasRegistradas();
                TareasAsignadas    = _db.GetTareasTotales();
                TareasProximas     = _db.GetTareasProximasAVencer();
                ProgresoAsesores   = _db.GetProgresoAsesores();
                Asesores           = _db.GetAsesores();

                CapacitacionesFinalizadas = _db.GetCapacitacionesFinalizadas();
                TotalEXP                  = _db.GetTotalEXP();
                TotalCertificados         = _db.GetTotalCertificados();
                PublicacionesRecientes   = _db.GetPublicacionesRecientes();

                LogroCapacitacionPorTodos  = _db.Logro_CapacitacionPorTodos();
                LogroEXP5000               = _db.Logro_EXP5000();
                LogroCincoCertificados     = _db.Logro_CincoCertificados();
                LogroCincoPublicaciones    = _db.Logro_CincoPublicacionesRecientes();
                LogroAsesorCincoMetas      = _db.Logro_AsesorCincoMetas();
                LogroTodosTiposCompletados = _db.Logro_TodosTiposCompletados();
                RankingAsesores            = _db.ObtenerTopAsesoresPorMetas();

                return Page(); 
                 
             }
 
             _db.InsertarTarea(NuevaTarea);
             ModelState.Clear(); 
             TempData["Mensaje"] = "Tarea asignada correctamente.";
 
             // Redirigir a GET para limpiar el formulario y recargar datos
             return RedirectToPage();
        }
    }
}

OxxoWeb/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Org.BouncyCastle.Bcpg;
using OxxoWeb.Models;

namespace OxxoWeb.Pages;

public class HomeModel : PageModel
{
    private readonly RecordatoriosDataBaseContext context;
    public List<Categoria> categorias { get; set; }
    public List<Recordatorio> recc { get; set; }
    public Dictionary<int, string> colores = new Dictionary<int, string>{
        {1,"morado"},{2,"amarillo"},{3,"rosa"},{0,"verde"}
    };
    //Diccionario para no repetir titulo de fecha
    public Dictionary<DateOnly, bool> Checkfecha = new Dictionary<DateOnly, bool>();
    public bool Checkfooter = false;
    public HomeModel(RecordatoriosDataBaseContext _context)
    {
        context = _context;
        //Inicializar
        categorias = new List<Categoria>();
        recc = new List<Recordatorio>();
    }
    public void OnGet()
    {
        // Checks if it has a user ID stored as int
        int? userId = HttpContext.Session.GetInt32("Id");
        if (userId == null)
        {
            // Takes user to login page
            Response.Redirect("/Index");
        }
        else
        {
            //Obtiene las categorías de tienda
            categorias = context.GetCategorias(userId.Value);
            //Asigna un color al boton de las categorías
            categorias.ForEach(categoria => categoria.color = colores[categoria.id_tienda % 4]);
            //Obtiene los recordatorios
            recc = context.GetRecordatorios(userId.Value);

            //Guarda la fechas de los recordatorios y si no esta en la lista las agrega
            foreach (var recordatorio in recc)
            {
                if (!Checkfecha.ContainsKey(recordatorio.fecha))
                {
                    Checkfecha.Add(recordatorio.fecha, false);
                }
            }
        }
    }
}

OxxoWeb/Pages/Juego.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using OxxoWeb.Models;

namespace OxxoWeb.Pages
{
    public class JuegoModel : PageModel
    {
        public AyudaVideojuego Ayuda { get; set; }

        public void OnGet()
        {
            // Instancia tu context (ajusta el nombre si cambiaste la clase)
            DatabaseContextJuego db = new DatabaseContextJuego();
            Ayuda = db.GetAyudaVideojuego();
        }
    }
}

OxxoWeb/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OxxoWeb.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

OxxoWeb/Pages/Recordatorios.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OxxoWeb.Models;

namespace OxxoWeb.Pages;

public class RecordatoriosModel : PageModel
{
    private readonly RecordatoriosDataBaseContext context;
    public List<Categoria> categorias { get; set; }
    public List<Recordatorio> recc { get; set; }
    //Diccionario para colores
    public Dictionary<int, string> colores = new Dictionary<int, string>{
        {1,"morado"},{2,"amarillo"},{3,"rosa"},{0,"verde"}
    };
    //Diccionario para no repetir titulo de fecha
    public Dictionary<DateOnly, bool> Checkfecha = new Dictionary<DateOnly, bool>();

    // Properties to match the fields used in the Razor page
    public string titulo { get; set; }
    public string descripcion { get; set; }
    public int id_tienda { get; set; }
    public DateOnly fecha { get; set; }
    public TimeSpan hora_inicio { get; set; }
    public TimeSpan hora_fin { get; set; }
    public string lugar {get;set;}
    public RecordatoriosModel(RecordatoriosDataBaseContext _context)
    {
        context = _context;
        //Inicializar
        categorias = new List<Categoria>();
        recc = new List<Recordatorio>();
    }
    public void OnGet()
    {
        // Checks if it has a user ID stored as int
        int? userId = HttpContext.Session.GetInt32("Id");
        if (userId == null)
        {
            // Takes user to login page
            Response.Redirect("/Index");
        }
        else
        {
            //Obtiene las categorías de tienda
            categorias = context.GetCategorias(userId.Value);
            //Asigna un color al boton de las categorías
            categorias.ForEach(categoria => categoria.color = colores[categoria.id_tienda % 4]);
            //Obtiene los recordatorios
            recc = context.GetRecordatorios(userId.Value);

            //Guarda la fechas de los recordatorios y si no esta en la lista las agrega
            foreach (var recordatorio in recc)
            {
                if (!Checkfecha.ContainsKey(recordatorio.fecha))
                {
                    Checkfecha.Add(recordatorio.fecha, false);
                }
            }
        }
    }

    //Tarea asyncrona de borrar
    public async Task<IActionResult> OnPostEliminar()
    {
        //Request.For para traerse el dato del input que es string y lo pasa a entero
        int id_recordatorio = int.Parse(Request.Form["id_rec"].ToString());
        //Task.Run espera a terminar esta tarea para después proceder, lo ejecuta en un subproceso separado.
        await Task.Run(() => context.EliminarRec(id_recordatorio));
        //Recargar pagina
        return RedirectToPage();
    }
    //Tarea asincrona para agregar
    public async Task<IActionResult> OnPostAgregar()
    {
        //Si el value de id_tienda recolectado del dropdown es 0 es personal si es mayor a 0 es de alguna tienda
        int id_tipo = int.Parse(Request.Form["id_tienda"]) == 0 ? 1 : 2;
        //Permite que descripcion sea empty o null
        string descripcion = Request.Form["descripcion"].ToString() ?? string.Empty;

        // Asegura que la fecha se procese correctamente
        string fechaInput = Request.Form["fecha"];
        fecha = DateOnly.ParseExact(fechaInput, "yyyy-MM-dd");

        // Insertar el nuevo recordatorio en la base de datos
        await Task.Run(() => context.AgregarRec(
            HttpContext.Session.GetInt32("Id").Value, 
            Request.Form["titulo"], 
            fecha, 
            Request.Form["lugar"], 
            descripcion, 
            TimeSpan.Parse(Request.Form["hora_inicio"]), 
            TimeSpan.Parse(Request.Form["hora_fin"]), 
            int.TryParse(Request.Form["id_tienda"], out int idTienda) && idTienda != 0 ? idTienda : (int?)null, 
            id_tipo)
        );
        
        return RedirectToPage();
    }
    public async Task<IActionResult> OnPostModificar()
    {
        //Recopila el id del recordatorio
        int id_recordatorio = int.Parse(Request.Form["id_recordatorio"].ToString());
        int id_tipo = int.Parse(Request.Form["id_tienda"]) == 0 ? 1 : 2;
        string descripcion = Request.Form["descripcion"].ToString() ?? string.Empty;

        // Asegura de que la fecha se procese correctamente
        string fechaInput = Request.Form["fecha"];
        fecha = DateOnly.ParseExact(fechaInput, "yyyy-MM-dd");

        // Insertar el nuevo recordatorio en la base de datos
        await Task.Run(() => context.ModificarRec(
            id_recordatorio, 
            Request.Form["titulo"], 
            fecha, 
            Request.Form["lugar"], 
            descripcion, 
            TimeSpan.Parse(Request.Form["hora_inicio"]), 
            TimeSpan.Parse(Request.Form["hora_fin"]), 
            int.TryParse(Request.Form["id_tienda"], out int idTienda) && idTienda != 0 ? idTienda : (int?)null, 
            id_tipo)
        );
        return RedirectToPage();
    }
}

OxxoWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    ViewData["HideHeader"] = true; // Indicar que esta página no debe mostrar el header
}

<div class="login-full-container bckColor">
    <!-- Imagen izquierda -->
    <div class="login-side-image-container left">
        <img src="~/img/backGroundImgIzquierda.png" class="login-side-image">
    </div>
    
    <!-- Contenido central (formulario de login) -->
    <div class="login-central-container">
        <div class="login-central-content">
            <div class="ImgOxx">
                <img class="ImgOxx mx-auto d-block" src="~/img/OxxoLogo.svg.png" alt="Imagen de OxxoLogo jaja alt xd">
            </div>
            <div class="text-center Titillium">
                <div class="PrimerText">
                    Iniciar sesión
                </div>
                <div class="SegundoTexto Titillium">
                    Introduce tus datos para continuar
                </div>
            </div>
            <form method="post">
                <div class="ContenedoresLogin">
                    <input type="text" asp-for="Username" placeholder="Usuario" />
                </div>
                <br>
                <div class="ContenedoresLogin" id="Contraseña">
                    <input type="password" asp-for="Password" placeholder="Contraseña" />
                </div>
                <br>
                <br>
                <div class="Enter">
                    <input type="submit" value="Ingresar">
                </div>
            </form>
            @if (!string.IsNullOrEmpty(Model.ErrorMessage))
            {
                <div class="alert alert-danger text-center mt-3">
                    @Model.ErrorMessage
                </div>
            }
        </div>
    </div>
    
    <!-- Imagen derecha -->
    <div class="login-side-image-container right">
        <img src="~/img/backGroundImgDerecha.png" class="login-side-image">
    </div>
</div>

OxxoWeb/Pages/Recordatorios.cshtml
@page
@model RecordatoriosModel

@{
    ViewData["Title"] = "Recordatorios";
}
<div class="row align-items-center Titillium">
    <div class="col-3">
        <h1>@ViewData["Title"]</h1>
    </div>
    <div class="col-8"></div>
    <div class="col-1">
        <button type="button" class="btn btn-primary plus" data-bs-toggle="modal" data-bs-target="#Agregar">
            <span class="material-symbols-outlined">add</span>
        </button>
        <!-- Modal -->
        <div class="modal fade" id="Agregar" tabindex="-1" aria-labelledby="AgregarLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content background-beige-cell">
                    <div class="modal-header">
                        <h1 class="modal-title titulo" id="AgregarLabel">Agregar recordatorio</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-page-handler="Agregar">
                            <div class="mb-3">
                                <input type="text" class="form-control Titillium" placeholder="Agregar título" asp-for="titulo" required></input>
                            </div>
                            <div class="mb-3">
                                <textarea class="form-control Titillium" placeholder="Descripción" rows="3" asp-for="descripcion"></textarea>
                            </div>
                            <div class="form-floating">
                                <select class="form-select" id="floatingSelect" asp-for="id_tienda" required>
                                    <option value="" disabled selected>Selecciona una categoría</option>
                                    <option value="0">Personal</option>
                                    @foreach(var tienda in Model.categorias){
                                        <option value="@tienda.id_tienda">@tienda.nombre_calle</option>
                                    }
                                </select>
                                <label for="floatingSelect">Categoría</label>
                            </div>
                            <div class="mb-3 margenarriba">
                                <input type="text" class="form-control Titillium" placeholder="Agregar lugar" asp-for="lugar" required></input>
                            </div>
                            <div class="mb-3 d-flex margenarriba">
                                <div class="form-floating">
                                    <input id="fecha" class="form-control" type="date" asp-for="fecha" value="@DateTime.Now.ToString("yyyy-MM-dd")" required />
                                    <label for="fecha">Fecha</label>
                                </div>
                                <div class="form-floating">
                                    <input id="horainicio" class="form-control" type="time" asp-for="hora_inicio" required />
                                    <label for="horainicio">Hora de inicio</label>
                                </div>
                                <div class="form-floating">
                                    <input id="horafin" class="form-control" type="time" asp-for="hora_fin" required />
                                    <label for="horafin">Hora de fin</label>
                                </div>
                            </div>
                        
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary botoncerrar"
                                    data-bs-dismiss="modal">Cerrar</button>
                                <button type="submit" class="btn btn-primary botonagregar">Agregar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row align-items-center Titillium">
    <div class="row g-6 align-items-start">
        <div class="col-3 background-beige-cell rounded p-3 align-items-end shadow-sm categoriees">
            <h2 class="titulo Titillium">Categoría</h2>
            <div class="mini_categoria">
                <input type="checkbox" class="btn-check" id="btn-check-personal"  value="0" autocomplete="off">
                <label class="btn btn-outline-primary botonpersonal" for="btn-check-personal"></label><br>
                <h3 class="mini_titulo Titillium">Personal</h3>
            </div>
            @if (Model.categorias.Count > 0)
            {
                @foreach (var tienda in Model.categorias)
                {
                    <div class="mini_categoria">
                        <input type="checkbox" class="btn-check" name="catselect" id="btn-check-@tienda.id_tienda"  value="@tienda.id_tienda" autocomplete="off">
                        <label class="btn btn-outline-primary @tienda.color" for="btn-check-@tienda.id_tienda"></label><br>
                        <h3 class="mini_titulo Titillium">Sucursal @tienda.nombre_calle</h3>
                    </div>
                }
            }

        </div>
        <div class="col-1"></div>
        <div class="col-8">
            @if(Model.recc == null || !Model.recc.Any()){
                //Cuando no hay recordatorios
                <h2 class="fechita Titillium">No hay recordatorios aún</h2>
            }
            @foreach(var rec in Model.recc){
                @if(!Model.Checkfecha[rec.fecha]){
                    //Extrae solamente la fecha y la compara con la fecha de la base de datos
                    @if(rec.fecha == DateOnly.FromDateTime(DateTime.Today)){
                        <h2 class="fechita Titillium">Hoy, @rec.fecha.ToString("dd 'de' MMMM 'del' yyyy")</h2>
                    }
                    else{
                        <h2 class="fechita Titillium">@rec.fecha.ToString("dd 'de' MMMM 'del' yyyy")</h2>
                    }
                    Model.Checkfecha[rec.fecha]=true;
                }
            <div class="flexible espacito">
                <button type="button" class="btn btn-primary botonsito @(rec.tipo == 't' ? @Model.colores[(rec.id_tienda ?? 0) % 4] : "botonpersonal")" data-bs-toggle="modal"
                    data-bs-target="#Modificar-@rec.id_recordatorio"></button>
                <div class="modal fade" id="Modificar-@rec.id_recordatorio" tabindex="-1" aria-labelledby="ModificarLabel-@rec.id_recordatorio"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content background-beige-cell">
                            <div class="modal-header">
                                <h1 class="modal-title titulo" id="ModificarLabel-@rec.id_recordatorio Titillium">Modificar recordatorio</h1>
                                <form method="post" asp-page-handler="Eliminar" class="modal-footer borrador margenmas">
                                    <input type="hidden" name="id_rec" value="@rec.id_recordatorio" />
                                    <button type="submit" class="material-symbols-outlined boradorsito">Delete</button>
                                </form>
                                <button type="button" class="btn-close margencero" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body Titillium">
                                <form method="post" asp-page-handler="Modificar">
                                    <input type="hidden" name="id_recordatorio" value="@rec.id_recordatorio" />
                                    <div class="mb-3">
                                        <input type="text" class="form-control Titillium" placeholder="Agregar título" value="@rec.titulo" asp-for="titulo" required />
                                    </div>
                                    <div class="mb-3">
                                        <input class="form-control Titillium" placeholder="Descripción" rows="3" asp-for="descripcion" value="@rec.descripcion"/>
                                    </div>
                                    <div class="form-floating">
                                        <select class="form-select" id="floatingSelect" asp-for="id_tienda" required>
                                            <option value="" disabled>Selecciona una categoría</option>
                                            <option value="0" selected="@(rec.id_tienda == 0)">Personal</option>
                                            @foreach(var tienda in Model.categorias)
                                            {
                                                <option value="@tienda.id_tienda" selected="@(rec.id_tienda == tienda.id_tienda)">@tienda.nombre_calle</option>
                                            }
                                        </select>
                                        <label for="floatingSelect">Categoría</label>
                                    </div>
                                    <div class="mb-3 margenarriba">
                                        <input type="text" class="form-control Titillium" placeholder="Agregar lugar" value="@rec.lugar" asp-for="lugar" required />
                                    </div>
                                    <div class="mb-3 d-flex margenarriba">
                                        <div class="form-floating">
                                            <input id="fecha" class="form-control" type="date" asp-for="fecha" value="@rec.fecha.ToString("yyyy-MM-dd")" required />
                                            <label for="fecha">Fecha</label>
                                        </div>
                                        <div class="form-floating">
                                            <input id="horainicio" class="form-control" type="time" asp-for="hora_inicio" value="@rec.hora_inicio.ToString("hh\\:mm")" required />
                                            <label for="horainicio">Hora de inicio</label>
                                        </div>
                                        <div class="form-floating">
                                            <input id="horafin" class="form-control" type="time" asp-for="hora_fin" value="@rec.hora_final.ToString("hh\\:mm")" required />
                                            <label for="horafin">Hora de fin</label>
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary botoncerrar" data-bs-dismiss="modal">Cerrar</button>
                                        <button type="submit" class="btn btn-primary botonagregar">Modificar</button>
                                    </div>
                                </form>

                               
                            </div>
                        </div>
                    </div>
                </div>
                <div class="rounded p-3 background-beige-cell align-items-end shadow-sm contenedorrec">
                    <div class="flexible espacio widht100">
                        <div class="Titillium titulo paddtit">@rec.titulo</div>
                        <div class="Titillium hora">@rec.hora_inicio.ToString("hh\\:mm") - @rec.hora_final.ToString("hh\\:mm")</div>
                    </div>
                    <div class="Titillium hora">@rec.lugar</div>
                </div>  
            </div>
            }
        </div>
    </div>
</div>